### ISSUE TITLE
Not compatible with RTL languages

### ISSUE THREAD

**Issue by ChrisBAshton** [bbc/gel-grid#37]
I may be missing something, but the following CSS in `gel-grid` is breaking our RTL typography.

```css
.gel-layout {
    direction: ltr;
    text-align: left;
}

.gel-layout__item {
    text-align: left;
}
```

Historically our Visual Journalism projects have been able to have a single class at the body level (`.bbc-news-vj-direction--rtl { direction: rtl; }`) and our RTL projects have "just worked". Now that we're using GEL grid in our projects, we'll have to specify overrides for the classes above.

Is there a strong reason why we need the `text-align` and `direction` properties defined in the grid itself?
